# Generated by Django 5.2.6 on 2025-09-23 17:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InformacoesFuncionais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_guerra', models.CharField(blank=True, max_length=100)),
                ('matricula', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('posto_graduacao', models.CharField(blank=True, choices=[('coronel', 'Coronel'), ('tenente_coronel', 'Tenente-Coronel'), ('major', 'Major'), ('capitao', 'Capitão'), ('tenente', 'Tenente'), ('subtenente', 'Subtenente'), ('sargento', 'Sargento'), ('cabo', 'Cabo'), ('soldado', 'Soldado')], max_length=50)),
                ('data_admissao', models.DateField(blank=True, null=True)),
                ('banco', models.CharField(blank=True, max_length=100)),
                ('agencia', models.CharField(blank=True, max_length=20)),
                ('conta_corrente', models.CharField(blank=True, max_length=30)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='info_funcionais', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_documento', models.CharField(max_length=255)),
                ('arquivo', models.FileField(upload_to='documentos/')),
                ('info_funcional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='funcional.informacoesfuncionais')),
            ],
        ),
    ]
