# Generated by Django 5.2.6 on 2025-09-23 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcional', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='arquivo',
            field=models.FileField(upload_to='documentos/', verbose_name='Arquivo'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='nome_documento',
            field=models.CharField(max_length=255, verbose_name='Nome do Documento'),
        ),
        migrations.AlterField(
            model_name='informacoesfuncionais',
            name='agencia',
            field=models.CharField(blank=True, max_length=20, verbose_name='Agência'),
        ),
        migrations.AlterField(
            model_name='informacoesfuncionais',
            name='banco',
            field=models.CharField(blank=True, max_length=100, verbose_name='Banco'),
        ),
        migrations.AlterField(
            model_name='informacoesfuncionais',
            name='conta_corrente',
            field=models.CharField(blank=True, max_length=30, verbose_name='Conta Corrente'),
        ),
        migrations.AlterField(
            model_name='informacoesfuncionais',
            name='data_admissao',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Admissão'),
        ),
        migrations.AlterField(
            model_name='informacoesfuncionais',
            name='matricula',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Matrícula'),
        ),
        migrations.AlterField(
            model_name='informacoesfuncionais',
            name='nome_guerra',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nome de Guerra'),
        ),
        migrations.AlterField(
            model_name='informacoesfuncionais',
            name='posto_graduacao',
            field=models.CharField(blank=True, choices=[('coronel', 'Coronel'), ('tenente_coronel', 'Tenente-Coronel'), ('major', 'Major'), ('capitao', 'Capitão'), ('tenente', 'Tenente'), ('subtenente', 'Subtenente'), ('sargento', 'Sargento'), ('cabo', 'Cabo'), ('soldado', 'Soldado')], max_length=50, verbose_name='Posto/Graduação'),
        ),
    ]
