# Generated by Django 5.2.6 on 2025-09-24 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcional', '0002_alter_documento_arquivo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informacoesfuncionais',
            name='posto_graduacao',
            field=models.CharField(blank=True, choices=[('coronel', 'Coronel'), ('tenente_coronel', 'Tenente-Coronel'), ('major', 'Major'), ('capitao', 'Capitão'), ('tenente', 'Tenente'), ('aspirante', 'Aspirante'), ('subtenente', 'Subtenente'), ('sargento', 'Sargento'), ('cabo', 'Cabo'), ('soldado', 'Soldado')], max_length=50, verbose_name='Posto/Graduação'),
        ),
    ]
