# Generated by Django 5.2.6 on 2025-09-23 17:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InformacoesPessoais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(blank=True, max_length=255)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='fotos_pessoais/')),
                ('cpf', models.CharField(blank=True, max_length=14, null=True, unique=True)),
                ('rg', models.CharField(blank=True, max_length=20)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('idade', models.PositiveIntegerField(blank=True, editable=False, null=True)),
                ('grupo_sanguineo', models.CharField(blank=True, max_length=5)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('estado_civil', models.CharField(blank=True, choices=[('solteiro', 'Solteiro(a)'), ('casado', 'Casado(a)'), ('divorciado', 'Divorciado(a)'), ('viuvo', 'Viúvo(a)')], max_length=20)),
                ('escolaridade', models.CharField(blank=True, choices=[('fundamental', 'Ensino Fundamental'), ('medio', 'Ensino Médio'), ('superior', 'Ensino Superior'), ('pos_graduacao', 'Pós-Graduação')], max_length=20)),
                ('cnh_numero', models.CharField(blank=True, max_length=20, null=True)),
                ('cnh_categoria', models.CharField(blank=True, max_length=5, null=True)),
                ('cnh_validade', models.DateField(blank=True, null=True)),
                ('titulo_eleitor', models.CharField(blank=True, max_length=30)),
                ('zona', models.CharField(blank=True, max_length=10)),
                ('secao', models.CharField(blank=True, max_length=10)),
                ('municipio_votacao', models.CharField(blank=True, max_length=100)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='info_pessoais', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
