# Generated by Django 5.2.6 on 2025-09-23 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informacoespessoais',
            name='cnh_categoria',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Categoria da CNH'),
        ),
        migrations.AlterField(
            model_name='informacoespessoais',
            name='cnh_numero',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Nº da CNH'),
        ),
        migrations.AlterField(
            model_name='informacoespessoais',
            name='cnh_validade',
            field=models.DateField(blank=True, null=True, verbose_name='Validade da CNH'),
        ),
        migrations.AlterField(
            model_name='informacoespessoais',
            name='cpf',
            field=models.CharField(blank=True, max_length=14, null=True, unique=True, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='informacoespessoais',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Nascimento'),
        ),
        migrations.AlterField(
            model_name='informacoespessoais',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='informacoespessoais',
            name='escolaridade',
            field=models.CharField(blank=True, choices=[('fundamental', 'Ensino Fundamental'), ('medio', 'Ensino Médio'), ('superior', 'Ensino Superior'), ('pos_graduacao', 'Pós-Graduação')], max_length=20, verbose_name='Escolaridade'),
        ),
        migrations.AlterField(
            model_name='informacoespessoais',
            name='estado_civil',
            field=models.CharField(blank=True, choices=[('solteiro', 'Solteiro(a)'), ('casado', 'Casado(a)'), ('divorciado', 'Divorciado(a)'), ('viuvo', 'Viúvo(a)')], max_length=20, verbose_name='Estado Civil'),
        ),
        migrations.AlterField(
            model_name='informacoespessoais',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_pessoais/', verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='informacoespessoais',
            name='grupo_sanguineo',
            field=models.CharField(blank=True, max_length=5, verbose_name='Grupo Sanguíneo'),
        ),
        migrations.AlterField(
            model_name='informacoespessoais',
            name='idade',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True, verbose_name='Idade'),
        ),
        migrations.AlterField(
            model_name='informacoespessoais',
            name='municipio_votacao',
            field=models.CharField(blank=True, max_length=100, verbose_name='Município de Votação'),
        ),
        migrations.AlterField(
            model_name='informacoespessoais',
            name='nome_completo',
            field=models.CharField(blank=True, max_length=255, verbose_name='Nome Completo'),
        ),
        migrations.AlterField(
            model_name='informacoespessoais',
            name='rg',
            field=models.CharField(blank=True, max_length=20, verbose_name='RG'),
        ),
        migrations.AlterField(
            model_name='informacoespessoais',
            name='secao',
            field=models.CharField(blank=True, max_length=10, verbose_name='Seção Eleitoral'),
        ),
        migrations.AlterField(
            model_name='informacoespessoais',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='informacoespessoais',
            name='titulo_eleitor',
            field=models.CharField(blank=True, max_length=30, verbose_name='Título de Eleitor'),
        ),
        migrations.AlterField(
            model_name='informacoespessoais',
            name='zona',
            field=models.CharField(blank=True, max_length=10, verbose_name='Zona Eleitoral'),
        ),
    ]
