# Generated by Django 5.2.6 on 2025-09-23 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familiar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filho',
            name='data_nascimento',
            field=models.DateField(verbose_name='Data de Nascimento'),
        ),
        migrations.AlterField(
            model_name='filho',
            name='idade',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True, verbose_name='Idade'),
        ),
        migrations.AlterField(
            model_name='filho',
            name='nome',
            field=models.CharField(max_length=255, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='informacoesfamiliares',
            name='bairro',
            field=models.CharField(blank=True, max_length=100, verbose_name='Bairro'),
        ),
        migrations.AlterField(
            model_name='informacoesfamiliares',
            name='cep',
            field=models.CharField(blank=True, max_length=9, verbose_name='CEP'),
        ),
        migrations.AlterField(
            model_name='informacoesfamiliares',
            name='cidade',
            field=models.CharField(blank=True, max_length=100, verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='informacoesfamiliares',
            name='complemento',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Complemento'),
        ),
        migrations.AlterField(
            model_name='informacoesfamiliares',
            name='conjuge_data_nascimento',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Nascimento do Cônjuge'),
        ),
        migrations.AlterField(
            model_name='informacoesfamiliares',
            name='conjuge_nome',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome do Cônjuge'),
        ),
        migrations.AlterField(
            model_name='informacoesfamiliares',
            name='endereco',
            field=models.CharField(blank=True, max_length=255, verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='informacoesfamiliares',
            name='numero_casa',
            field=models.CharField(blank=True, max_length=20, verbose_name='Número'),
        ),
    ]
